# Initial Brainstorming Org MAY 18th 

* Notes 
** If session gets full -- use the signs!!!
** Consider how to make workshop ACCESSIBLE
* TODO Game [0/7]
  - WORKING [ ] formalize rules/constraints #dc
  - [ ] write role cards
  - [ ] design role cards [0/1]
    - [ ] including chips
  - [ ] write event cards
  - [ ] consider signage for vacant roles
  - [ ] create props list
  - WORKING [ ] Preamble and Takeaway [0/2] #dc
    - WORKING [ ] initial introduction 
    - WORKING [ ] takeaway debrief
* TODO Running Questions 
  - [ ] making schematics for organizers, one per scenario
    - [ ] Does the map require building types specified?


* Workshop Breakdown
** 20 minute intro
  - Deliver Rules 
  - Assign Roles (know the distibution numbers)
    - Type/Skill
    - Neighbourhood
    - Network Chips
  - Move Outside
** 50 minute game-play
  - 2-3 scenarios of increasing difficulty with the same underlying framework
    - basic gameplay mechanics (data packets & network expansion)
    - introducing challenges
    - introducing time constraints
** 15 minute outro
  - AMC 4min feedback box
* Game Mechanics
** Players
  Minimum: 10 players
  - Scales to 20, 30
** Initial Introduction
  Today we are going to co-design a way for a couple of areas to communicate using community wireless technology. Everyone participating will create the solution by moving through the game we've prepared and resolving difficulties encountered. 

  With a session that is only 90 minutes long we are going to spend our time in the following way:
  - the first 20 minutes will be explaining the rules, handing out roles and getting outselves set up to play
  - we will spend roughly the next hour actually playing the game
  - the final 15 minutes will be an opportunity for everyone to report back about their experiences and take aways.

  We will mention this again at the end, but right now we are still in the early stages of exploring how play and this workshop can help design and create community networks.
** Objective
 The objective for the game is to collectively send enough messages around your local mesh network. To achieve this you will have to move around enough data packets and build new nodes to expand your network.
** Goal: 
 The game is structured into stages of increasing difficulty, the first stage will introduce the basic game with each following stage including a new element you'll have to overcome. Since we aren't working with hardware we will use the successful movement of enough people to signify a 'working' network.

 Each person should have one role card. Therea are three roles: Organizer, Technologist and Human. Each has elements or skills required for the expansion of a network. 

 <FILL IN WITH ROLE DESCRIPTION ONCE FINALIZED>

 As facilitators we will be around to both aid and hinder you as you go about your tasks


** Tasks (Actions)
  Will have to be completed by the group to fulfill some condition
*** Holding Community Meeting
  Rationale: 
  Requires:
*** Installing a Node
  Rationale: fundamental to moving chips around
  Requires: 
  - consensus/majority from area
  - organizers acquire chip from residents--- brings 50%+ to site 
  - viable site based on type of building/router/power
  - sucessful installation
*** Have Active Connection
  Rationale: 
  Requires:
  - somehow denote range with string... how do we deal with multidirectional broadcast?
** Events 
  Seemingly random occurences effecting everyone
*** environmental hazards
**** trees falling, downed lines
***** rewards for completion
*** static obstacles
**** construction
**** trees/tall buildings in the way
*** network topography (node spacing)
** What is the victory condition?
*** some number of countable exchanges on a network
** Number of participants: 8-30 (???) -> This needs to be informed by prototype run through
** Set up for play: 
 - Organizer allocate role cards depending on group size (be aware of what was handed out) 
 - If any roles are vacant than ensure those props are present


** Takeaway Debrief
  <some way to get participants attention, maybe described or determined at the beginning of the play session>

  Given that we are out of time I





