* Rules 
  DRAFT 2015-06-13

** Workshop Breakdown
*** 20 minute intro
  - Deliver Rules 
  - Assign Roles (know the distribution numbers)
    - Type/Skill
    - Neighbourhood
    - Network Chips
  - Move Outside
*** 50 minute game-play
  - 2-3 scenarios of increasing difficulty with the same underlying framework
    - basic gameplay mechanics (data packets & network expansion)
    - introducing challenges
    - introducing time constraints
*** 15 minute outro


** Players
  Minimum: 10 players
  - Scales to 20, 30ish increments with suggested breakdowns of roles, hopefully some flexibility!

** Initial Introduction
  Today we are going to model a way for a group of people to communicate using community wireless technology using play!  

  With a session that is 90 minutes we expect to spend our time in the following way:
  - the first 20 minutes will be explaining the rules, handing out roles and getting ourselves set up to play (outside hopefully!)
  - we will spend roughly the next hour playing the game
  - the final 15 minutes will be an opportunity for everyone to talk about their experience and provide feedback to both us and AMC!

  We will mention this again at the end, but right now we are still in the early stages of exploring how play and this workshop can help with understanding and designing community networks and welcome and thoughts, feedback and experiences you have to share.

** Goal
  The goal of the game is for the community to collectively send enough messages around your local mesh network in the time that we have.

  To achieve this you will have to move enough data packets and build new nodes to expand your network.

** Objectives
  The game is structured into stages of increasing difficulty, the first stage will introduce the basic game with each following stage including a new element you'll have to overcome. Since we aren't working with hardware we will use the successful movement of enough people to signify a 'working' network.

  Each person should have one role card. There are three roles: Organizer, Technologist and Resident. Each has elements or skills required for the expansion of a network. _In addition_, Technologists and Residents have the ability to act as Data Packets when not working with the organizer resolve events and build new nodes.

*** Data Packets
  The main unit of progress is the number of data packets delivered. On the back of the Technologist and Resident role cards there is a guide showing the routes that have to be completed in sequence to be 

*** Resolving Events
  From time to time events will come up that get in the way of future progress, the organizer working with technologists and residents will have to overcome these challenges in order to maintain a healthy and functioning network!

*** Completing the Game
  Winning the Game, once you have completed a route ...

  <THIS NEEDS TO BE RESOLVED>

  The game will happen in rounds of increasing difficulty. To move to the next round all players will have to work together to achieve the group goal of delivering packets. The only way to do so is to balance building the network and delivering data packets!

  As facilitators we will be around to both aid and hinder you as you go about your tasks.

** Setup
*** Facilitator
**** Required Materials
  - (in handouts/)
   - Rules Printout
   - Role Cards 
     - 5 Organizers
     - 10 Technologists
     - 10/colour (C/M/Y) Residents
   - Event Cards
   - Node Broadcasting Signage
   - Additional Signage

 - Stakes or Pylons (Survey Stakes)
 - Sash for Organizers (?)

**** Role Card Allocation
  - Facilitator allocates role cards depending on group size 
    (including resident colour breakdown)
     People | Organizers  | Technologists | Residents || C | M | Y
    --------------------------------------------------||-----------
      10    |      1      |       2       |      7+   || 4 | 3 |   
      20    |      3      |       5       |     12+   || 5 | 4 | 3 
      30    |      4      |       7       |     19+   || 7 | 7 | 5 

**** Calculate Data Packets Goal
  Amount should scale based on the number of participants, the goal is roughly 50% (5/10) per person (including organizer roles), however the tally is pooled.

**** Initial Network Layout
  <FILL IN WITH FACILITATOR>

*** Participants
  - Organizers should be provided with a sash
  - Technologists should be provided with a ??

  - Players have to go and stand find a starting node with a "Broadcasting" sign that is not occupied by another player

** Sequence of Play
  Play is initiated by the Facilitators, they call out the beginning of the round, hand out event cards, verify that all conditions are met by Organizers to build a new node and that routes have been completed by players.

** Takeaway Debrief
  <get participants attention, maybe described or determined at the beginning of the play session>

  We want to leave enough time to talk and hear from everyone, as well as give enough time to complete session feedback for AMC.

  Some guidelines to give space for a wider range of people to speak:
  - Wait a couple seconds before jumping in, especially if we've spoken before
  - Can we use our twinkles when someone says something we appreciate or agree with and want to build on?

  We made some prompt questions, but please comment or reflect on any aspect of the session:
  - What was the biggest challenge when... 
    - Delivering data packets? 
    - Building network nodes?
  - How do you feel this game reflects the actual process of building a network?
  - What was your favourite part of playing the game?
    - What was your leave favourite?

  [when ~5 minutes left transition into AMC feedback]
