* Rules
  DRAFT 2015-06-13
** Workshop Breakdown
*** 15 minute intro and presentation

  - Deliver Rules
  - Assign Roles (know the distribution numbers)

*** 50 minute game-play
- 2-3 scenarios of increasing difficulty with the same underlying framework:
1. basic gameplay mechanics (data packets & network expansion)
2. introducing challenges
3. introducing time constraints

*** 15 minute outro

** Players
- Minimum: 10 players
  - Scales to 20, 30ish increments with suggested breakdowns of roles

** Initial Introduction
Today we are going to play out a scenario around the obstacles, challenges, and
advantages a community might face when decentralizing its wireless technology
infrastructure!

We have a session that is 90 minutes and we expect to spend:
- the first 15 minutes explaining some mesh concepts, going over the
  rules, handing out roles and getting ourselves set up to play
- we will spend roughly the next hour playing the game
- the final 15 minutes will be an opportunity for everyone to talk
  about their experience and shareback some of what they noticed

We will mention this again at the end, we are still in the early stages of
exploring how play and this workshop can enhance understanding community
networks. We welcome all thoughts, feedback, and experiences you might want to
share! This game or ideas from it may be incorporated in future research.

** Presentation: Intro to Mesh

*** Slide 1: Network Topology
Distributed communications networks can take many forms. There are three main types of network:

Centralized, where all nodes are connected to one single point that holds up the whole network.

Decentralized, where nodes are connected in clusters to a set of key high-level, or backbone nodes that bridge connections across groups (this is similar to how the internet currently looks).

Distributed, where connections are formed 'equally' between all nodes.

In a mesh network, connections can be formed between any two nodes as peers in order to flexible move traffic (or 'route' it) across the network. Each node can receive and also route information, leading to a very different 'shape' or 'topology' of the network.

*** Slide 2: Nodes, links

At the highest level, networks have two parts: nodes and links. any point in the network (such as a computer, or a router) is a network node. Any path between them is a link.

*** Slide 3: Routes and hops

When someone wants to send information from one node to another, they follow a route of links.

Each time data moves from one node to another, we call this a 'hop.'

*** Slide 4: Roles
Many different kinds of people are involved in creating community infrastructure... we've chosen to include some of these as roles in NodeRunner.

1. Organizers are responsible for motivating people and getting them to come together to solve problems.

2. Technologists have a deep understanding of the equipment and theory of networking, and are needed to set up equipment and troubleshoot problems with the network.

3. Residents are the stewards of the land that the network occupies. They have knowledge of their community, its people, and the power and desire to go out and get things done!

*** Slide 5: Equipment
At a high level, the following technical components are required in a mesh network:
1. Routers to decide how to move information (or data) across the network, in a mesh network, routers can talk to each other and flexibly direct traffic

2. Antennas which connect to the routers, to direct and broadcast  the signal both wide enough and above obstacles

3. Network, or Ethernet Cable to connect modems, routers and computers together

4. A power source to get it all running!

*** Slide 6: Roleplaying
NodeRunner is more fun if you roleplay (even just a bit). These are just some ideas- what you should really keep in mind is to be clear to others in the game who you are or what you represent to the community- even if you're just roleplaying yourself!

*** Slide 7:
Kathy installs an antenna for Red Hook wireless

Adam Longwill holds pittmesh antenna

Sick night shot of NYCmesh

Everyone loves Freifunk


** Goal
The goal of the game is for the community to collectively send ("data
packets") messages around its local mesh network in given amount of time.

To achieve this you will have to move enough data packets, build new nodes to
expand your network, and respond to challenges that arise as you go about this
primary goal.

** Objectives
The session is structured in stages of increasing difficulty:

*** First Stage
The first stage will introduce the game, with each following stage including
new challenges that players will have to overcome. Since we aren't working
with hardware, we will use the successful movement of enough "data packets"
to signify a 'working' network.

Each person should have one role card. There are three roles:
- Organizer
- Technologist
- Resident

Each has elements or skills required for the expansion of a network.

Technologists and Residents simultaneously act out Data Packets when not
working with each other to resolve events and build new nodes.

*** Data Packets
A successful outcome in the game is measured by the number of "data packets"
sent. On the back of the Technologist and Resident role cards there is a guide
showing the data packet routes that have to be completed in sequence.

<physically show example here>

*** Resolving Events
From time to time, events will come up that get in the way of future progress.
Organizers, working with technologists and residents, will have to overcome
these challenges in order to grow and maintain a healthy network!

<physically show example here>

*** Playing the Game
Once you have completed a "data packet" route, you can begin your next route
immediately.

The only conditions hampering your progress are:
- you cannot occupy the same node at the same time as someone else,
  however, you can pass over that node, or wait until they have moved on.
  - If you get stuck for a long time, call an organizer over and hey can figure
    out how to help.
  - If not, retrace your steps and start another route.

*** Later Stages
The game will happen in rounds of increasing difficulty. To move to the next
round all players will have to work together to achieve the group goal of
delivering packets. The only way to do so is to balance your activity
between building the network and sending messages!

As facilitators we will be around to both aid and hinder you as you go about
your tasks. If at any point you need clarification, flag one of us down.


** Setup
*** Facilitator
**** Required Materials
  - (in handouts/)
   - Rules Printout
   - Role Cards
     - 5 Organizers
     - 10 Technologists
     - 10/colour (C/M/Y) Residents
   - Event Cards
   - Node Broadcasting Signage
   - Additional Signage

 - Stakes or Pylons (Survey Stakes)
 - Sash for Organizers (?)

**** Role Card Allocation
  - Facilitator allocates role cards depending on group size
    (including resident colour breakdown)
     People | Organizers  | Technologists | Residents || C | M | Y
    --------------------------------------------------||-----------
      10    |      1      |       2       |      7+   || 4 | 3 |
      20    |      3      |       5       |     12+   || 5 | 4 | 3
      30    |      4      |       7       |     19+   || 7 | 7 | 5

**** Calculate Data Packets Goal
Amount should scale based on the number of participants, the goal is
roughly 50% (5/10) per person (including organizer roles), however
the tally is pooled.

**** Initial Network Layout


*** Participants
- Organizers should be provided with a sash

- Players have to find a starting node with that Broadcasting that is not
  occupied by another player

** Sequence of Play
Play is initiated by the Facilitators. They call out the beginning of the
round, hand out event cards, verify that all conditions are met by Organizers
to build a new node, and ensure that routes have been completed by players.

** Takeaway Debrief
<get participants attention, maybe described or determined at the
beginning of the play session>

Some guidelines to give space for a wider range of people to speak:
- Wait a couple seconds before jumping in, especially if we've spoken before

We made some prompt questions, but please comment or reflect on any
aspect of the session:
- What was the biggest challenge when...
  - Delivering data packets?
  - Building network nodes?
- How do you feel this game reflects the actual process of building a network?
- What was your favourite part of playing the game?
  - What was your least favourite?
- How could it be more accessible?
- Do you see this being effective for different age groups?

[when ~5 minutes left transition into AMC feedback]
